### ISSUE TITLE
benchmarks break on raven

### ISSUE THREAD

**Issue by poloskeipeter** [PrincetonUniversity/STELLOPT#268]
A clean STELLOPT was pulled, and the develop branch was checked out.

It was built with the following modules in a csh (but could be reproduced in bash too):

 1) git/2.43  2) intel/21.4.0   3) mkl/2021.2   4) impi/2021.4   5) hdf5-mpi/1.12.2   6) netcdf-mpi/4.8.1   7) fftw-mpi/3.3.10   8) anaconda/3/2020.02  

After trying to run make test_vmec it breaks with the following message:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  Could not load shared libraray libstell.so    !!
!!  PATH: /raven/u/$USER/src/STELLOPT/LIBSTELL/Release/libstell.so    !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "./compare.py", line 31, in <module>
    vmec.read_wout(f'wout_{run_name}.nc')
  File "../../pySTEL/libstell/vmec.py", line 35, in read_wout
    wout_dict = self.libStell.read_wout(filename)
  File "../../pySTEL/libstell/libstell.py", line 950, in read_wout
    read_wout = getattr(self.libstell,module_name+'_readw_and_open'+self.s3)
AttributeError: 'LIBSTELL' object has no attribute 'libstell'
make: *** [makefile:137: test_vmec] Error 1
```
make test_fieldlines goes through, though reporting:
```
=================
  STATUS: FAIL!!!!!
make[1]: *** [makefile:262: test_fieldlines_coll] Error 255

```

Similarly, errors were reported by @lvanham at make test_beams3d:

![image](https://github.com/user-attachments/assets/5571ec78-5a27-4d48-8b22-78eced98f591)

**Comment by lazersos** [comment]
@poloskeipeter It appears as if python can find the `libstell.so` file. From the `LIBSTELL` directory issue the command `make shared_release`. This should fix it if `libstell` is building correctly.

**Comment by lazersos** [comment]
@poloskeipeter Also check to make sure $USER is defined.

**Comment by poloskeipeter** [comment]
> @poloskeipeter Also check to make sure $USER is defined.

$USER is defined, and the file exists at the location where pySTEL would expect it to be.

I deleted .o files from LIBSTELL/Release and rebuilt it as you recommended. It still crashes with the same error message with the make_vmec benchmark.

**Comment by lazersos** [comment]
This is very odd because if the file is on the path the error shouldn't be there. From the `pySTEL` directory try issuing the command:
`python3 setup.py install --user`
See if that fixes it.

**Comment by poloskeipeter** [comment]
Did manually install pySTEL but it didn't help. Same error.
Maybe the following helps:
```
>>> import os, sys
>>> import ctypes as ct
>>> st_path = os.environ["STELLOPT_PATH"]
>>> libs_path = os.path.join(st_path,'LIBSTELL','Release','libstell.so')
>>> libs_path
'/raven/u/pepo/src/STELLOPT/LIBSTELL/Release/libstell.so'
>>> os.path.isfile(libs_path)
True
>>> self.libstell = ct.cdll.LoadLibrary(libs_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2020.02/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2020.02/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libssh.so.4: undefined symbol: EVP_KDF_CTX_new_id, version OPENSSL_1_1_1d
```

**Comment by lazersos** [comment]
@poloskeipeter This is a known issue with `libssh`, try a newer version of anaconda.

**Comment by poloskeipeter** [comment]
Replacing the anaconda module with the latest (anaconda/3/2023.03) does not resolve the problem.

**Comment by lazersos** [comment]
@poloskeipeter This seems like perhaps an MPCDF configuration issue. Open a ticket with them.  You can add this issue URL to the ticket so they can see what's happening.

**Comment by poloskeipeter** [comment]
From mpcdf helpdesk:

> this is an unfortunate issue with anaconda. It ships its own version of some common system libraries. In this particular case it is libcrypto.so.1.1 that clashes with /usr/lib64/libcrypto.so.1.1 (the latter despite being the same nominal version has some backported symbols). libstell now is intentionally compiled and linked against the systems libcrypto. But at runtime when loading from python, anaconda already put its own libcrypto in the namespace masking the system's one and leading to the error you see. One option would be to somehow tweak the compilation of stellopt to link against anaconda's libcrypto in the first place. A 'quick fix' would be to preload the relevant libraries before starting python with
> 
> export LD_PRELOAD=/usr/lib64/libcrypto.so.1.1:/usr/lib64/libssl.so.1.1

in the environment setup at remote (.bashrc or whatever sourcefile you use) you need to add the following:
`export LD_PRELOAD=/usr/lib64/libcrypto.so.1.1:/usr/lib64/libssl.so.1.1`
and you need to re-build the modules which might have dependencies. 
This seems to resolve the bug, now the test_vmec is running without crashing(I will close the issue once it completes).

Do you know which modules need to be recompiled? Or would you recommend just build_all?

**Comment by ksebaz** [comment]
My advice would be rather not to put it in the shell config but keep it locally. Even better just when invoking python:
```
LD_PRELOAD=/usr/lib64/libcrypto.so.1.1:/usr/lib64/libssl.so.1.1 python ....
```

**Comment by lazersos** [comment]
This fundamentally seems like an Anaconda issue. This only affects the Python helper utilities as all the main parts of the code are Fortran. I'm going to update our documentation regarding compiling for the MPCDF with the information from this posting.  After which I'm going to close the issue. A workaround is to just not use anaconda at all.

**Comment by lazersos** [comment]
OK I updated the documentation.
[STELLOPT Compilation on MPCDF Machines](https://princetonuniversity.github.io/STELLOPT/STELLOPT%20Compilation%20on%20MPCDF)
Issue closed.
